version: '3.4'

services:
  jupyter-lab:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        base_image: nvidia/cuda:11.4.2-devel-ubuntu20.04

    restart: always
    environment:
      - JUPYTER_CONFIG_PATH=/config/jupyter/jupyter_notebook_config.py
    volumes:
      - ./config/jupyter:/config/jupyter/
      - ./data/har_dataset:/data/har_dataset
      - ./:/workspace
      # Container path "/artifacts" should be the same as one in mlflow_tracker container
      - ${MLFLOW_ARTIFACTS_PATH}:/artifacts
    ports:
      - "${JUPYTER_EXPOSED_PORT}:8888"
    networks:
      - public
      - internal
    entrypoint: "/bin/bash"
    deploy:
      resources:
        limits:
          memory: ${JUPYTER_CONTAINER_MEM_LIMIT}
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: [
        "-c",
        "adduser --uid ${UID} --disabled-password --gecos '' ${USER}; 
        adduser ${USER} sudo ;
        echo '${USER} ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers ;
        su ${USER} -c '/usr/local/bin/jupyter-lab --notebook-dir=/workspace --config=/config/jupyter/jupyter_notebook_config.py'"
    ]

  # Ref: https://github.com/Toumash/mlflow-docker
  mlflow_db:
    image: mysql/mysql-server:5.7.28
    restart: unless-stopped
    container_name: mlflow_db
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
    networks:
      - internal

  mlflow:
    container_name: mlflow_tracker
    image: mflow
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/Dockerfile.mlflow
    volumes:
      - ${MLFLOW_ARTIFACTS_PATH}:/artifacts
    ports:
      - "${MLFLOW_EXPOSED_PORT}:5000"
    networks:
      - public
      - internal
    entrypoint: bash ./wait-for-it.sh mlflow_db:3306 -t 90 -- mlflow server --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mlflow_db:3306/${MYSQL_DATABASE} --default-artifact-root /artifacts -h 0.0.0.0

networks:
  internal:
  public:
    driver: bridge